<?php include "blocks/about-summit-block.php"; ?>
<?php include "blocks/summit-text-block.php"; ?>
<?php include "blocks/sessions-block.php"; ?>
<?php include "blocks/speakers-block.php"; ?>
<?php include "blocks/partners-block.php"; ?>
<?php include "blocks/reviews-block.php"; ?>
<?php include "blocks/news-block.php"; ?>
<?php include "blocks/summit-price-block.php"; ?>
<?php include "blocks/summit-registration-block.php"; ?>
<?php include "blocks/summit-contacts-block.php"; ?>
<?php include "blocks/location-block.php"; ?>